### ISSUE TITLE
Add guide how to download supported Steam version

### ISSUE THREAD

**Issue by Kubitini** [m1s3ry/crashlands-vita#4]
The patch does not work with current version of the game. Here's how to get game files of supported version on Steam:
1) Open the [Steam console](steam://nav/console)
2) Download specific version of the game by typing this command:
```
download_depot 391730 391731 750708251145921383
```
3) It may look like it doesn't do anything, but wait a few minutes
4) When the downloading is done, you will see this message:
```
Depot download complete : [PATH_TO_THE_DOWNLOADED_GAME_FILES]
```
5) Go to the folder and run the path there.

**Comment by m1s3ry** [comment]
Thanks a lot! Will add it to the main readme
